# Generated by Django 5.2.6 on 2025-09-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('payroll_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('headingText', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Payslip Group',
                'verbose_name_plural': 'Payslip Groups',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='eddefinition',
            options={'ordering': ['edCode'], 'verbose_name': 'ED Definition', 'verbose_name_plural': 'ED Definitions'},
        ),
        migrations.AlterField(
            model_name='eddefinition',
            name='edCodeAscending',
            field=models.CharField(db_column='edCodeAscending', db_index=True, max_length=20, unique=True),
        ),
        migrations.RenameField(
            model_name='eddefinition',
            old_name='edCodeAscending',
            new_name='edCode',
        ),
        migrations.AddField(
            model_name='eddefinition',
            name='payrollCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edDefinitions', to='payroll.payroll'),
        ),
        migrations.AddField(
            model_name='eddefinition',
            name='payslipText',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eddefinition',
            name='payslipGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edDefinitions', to='payroll_setup.payslipgroup'),
        ),
    ]
