# Generated by Django 5.2.6 on 2025-09-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('payroll_setup', '0002_payslipgroup_alter_eddefinition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eddefinition',
            name='calculationGroup',
            field=models.CharField(choices=[('None', 'None'), ('Payments', 'Payments'), ('Benefit non cash', 'Benefit non cash'), ('Deduction', 'Deduction')], default='None', max_length=32),
        ),
        migrations.AddField(
            model_name='eddefinition',
            name='postingType',
            field=models.CharField(choices=[('None', 'None'), ('G/L Account', 'G/L Account'), ('Direct', 'Direct'), ('Customer', 'Customer'), ('Vendor', 'Vendor')], default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='eddefinition',
            name='edCode',
            field=models.CharField(db_index=True, help_text='ED stands for Earnings and Deductions.', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='EdPostingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edPostingGroup', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('payrollCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edPostingGroups', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'ED Posting Group',
                'verbose_name_plural': 'ED Posting Groups',
                'ordering': ['edPostingGroup'],
            },
        ),
        migrations.AddField(
            model_name='eddefinition',
            name='edPostingGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edDefinitions', to='payroll_setup.edpostinggroup'),
        ),
    ]
