# Generated by Django 5.2.6 on 2025-09-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('payroll', '0001_initial'),
        ('payroll_setup', '0003_eddefinition_calculationgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePostingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postingGroup', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('payrollCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeePostingGroups', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Employee Posting Group',
                'verbose_name_plural': 'Employee Posting Groups',
                'ordering': ['postingGroup'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPostingSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditAccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditPayrollPostingSetups', to='financial.glaccount', verbose_name='Credit Account')),
                ('debitAccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debitPayrollPostingSetups', to='financial.glaccount', verbose_name='Debit Account')),
                ('edPostingGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollPostingSetups', to='payroll_setup.edpostinggroup')),
                ('employeePostingGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrollPostingSetups', to='payroll_setup.employeepostinggroup')),
            ],
            options={
                'verbose_name': 'Payroll Posting Setup',
                'verbose_name_plural': 'Payroll Posting Setups',
                'unique_together': {('employeePostingGroup', 'edPostingGroup')},
            },
        ),
    ]
