# Generated by Django 5.2.6 on 2025-09-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('payroll_setup', '0004_employeepostinggroup_payrollpostingsetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollpostingsetup',
            name='creditAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creditPayrollPostingSetups', to='financial.glaccount', verbose_name='Credit Account'),
        ),
        migrations.AlterField(
            model_name='payrollpostingsetup',
            name='debitAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debitPayrollPostingSetups', to='financial.glaccount', verbose_name='Debit Account'),
        ),
    ]
