# Generated by Django 5.2.6 on 2025-09-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('payroll_setup', '0005_alter_payrollpostingsetup_creditaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipgroup',
            name='payrollCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payslipGroups', to='payroll.payroll'),
        ),
    ]
