# Generated by Django 5.2.6 on 2025-09-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0006_payslipgroup_payrollcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='eddefinition',
            name='debitCredit',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10, null=True, verbose_name='Debit/Credit'),
        ),
    ]
