# Generated by Django 5.2.6 on 2025-09-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('payroll_setup', '0007_eddefinition_debitcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schemeId', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Scheme ID')),
                ('description', models.CharField(max_length=255)),
                ('payrollCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculationHeaders', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Calculation Header',
                'verbose_name_plural': 'Calculation Headers',
                'ordering': ['schemeId'],
            },
        ),
    ]
