# Generated by Django 5.2.6 on 2025-09-18 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0008_calculationheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSchemeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNo', models.PositiveIntegerField(verbose_name='Line No.')),
                ('description', models.CharField(max_length=255)),
                ('calculation', models.CharField(choices=[('None', 'None'), ('Add', 'Add'), ('Subtract', 'Subtract'), ('Multiply', 'Multiply'), ('Divide', 'Divide'), ('Percent', 'Percent'), ('Highest', 'Highest'), ('Lowest', 'Lowest'), ('Look Up', 'Look Up')], default='None', max_length=20, verbose_name='Calculation')),
                ('computeTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computedFrom', to='payroll_setup.calculationschemeline', verbose_name='Compute To')),
                ('payrollEntry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculationLines', to='payroll_setup.eddefinition', verbose_name='Payroll Entry')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemeLines', to='payroll_setup.calculationheader', verbose_name='Scheme ID')),
            ],
            options={
                'verbose_name': 'Calculation Scheme Line',
                'verbose_name_plural': 'Calculation Scheme Lines',
                'ordering': ['scheme', 'lineNo'],
                'unique_together': {('scheme', 'lineNo')},
            },
        ),
    ]
