# Generated by Django 5.2.6 on 2025-09-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0009_calculationschemeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNo', models.PositiveIntegerField(verbose_name='Line No.')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Calculation Lookup',
                'verbose_name_plural': 'Calculation Lookups',
                'ordering': ['lineNo'],
            },
        ),
    ]
