# Generated by Django 5.2.6 on 2025-09-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0010_calculationlookup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculationLookup',
        ),
        migrations.RemoveField(
            model_name='calculationschemeline',
            name='computeTo',
        ),
        migrations.AddField(
            model_name='calculationschemeline',
            name='calculationLine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculationLines', to='payroll_setup.calculationschemeline', verbose_name='Calculation Line'),
        ),
    ]
