# Generated by Django 5.2.6 on 2025-09-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0011_delete_calculationlookup_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalculationSchemeLine',
            new_name='CalculationScheme',
        ),
    ]
