# Generated by Django 5.2.6 on 2025-09-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0012_rename_calculationschemeline_calculationscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationscheme',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemeLines', to='payroll_setup.calculationheader', verbose_name='Scheme'),
        ),
    ]
