# Generated by Django 5.2.6 on 2025-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0013_alter_calculationscheme_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationscheme',
            name='payrollEntry',
        ),
        migrations.AddField(
            model_name='calculationscheme',
            name='Input',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Calculation Line', 'Calculation Line'), ('Payroll Entry', 'Payroll Entry')], default='None', max_length=20, null=True, verbose_name='Input'),
        ),
    ]
