# Generated by Django 5.2.6 on 2025-09-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0014_remove_calculationscheme_payrollentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationscheme',
            name='payrollEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calculationSchemes', to='payroll_setup.eddefinition', verbose_name='Payroll Entry'),
        ),
    ]
