# Generated by Django 5.2.6 on 2025-09-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0015_calculationscheme_payrollentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationscheme',
            name='roundPrecision',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Round Precision'),
        ),
        migrations.AddField(
            model_name='calculationscheme',
            name='roundType',
            field=models.CharField(choices=[('None', 'None'), ('Up', 'Up'), ('Down', 'Down'), ('Nearest', 'Nearest')], default='Nearest', max_length=10, verbose_name='Round'),
        ),
    ]
