# Generated by Django 5.2.6 on 2025-09-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_currency'),
        ('payroll', '0001_initial'),
        ('payroll_setup', '0016_calculationscheme_roundprecision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationscheme',
            name='calculateTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculatedFrom', to='payroll_setup.calculationscheme', verbose_name='Calculate To'),
        ),
        migrations.AddField(
            model_name='calculationscheme',
            name='divideMultiply',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Divide/Multiply'),
        ),
        migrations.AddField(
            model_name='calculationscheme',
            name='fCalculation',
            field=models.CharField(choices=[('None', 'None'), ('Add', 'Add'), ('Subtract', 'Subtract'), ('Multiply', 'Multiply'), ('Divide', 'Divide'), ('Percent', 'Percent'), ('Highest', 'Highest'), ('Lowest', 'Lowest'), ('Look Up', 'Look Up')], default='None', max_length=20, verbose_name='fCalculation'),
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('localServiceTax', models.BooleanField(default=False, verbose_name='Local Service Tax')),
                ('type', models.CharField(choices=[('Percentage', 'Percentage'), ('Extract Amount', 'Extract Amount'), ('Month', 'Month'), ('Max Min', 'Max Min'), ('Special', 'Special')], max_length=20, verbose_name='Type')),
                ('minExtractAmountLCY', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min Extract Amount (LCY)')),
                ('maxExtractAmountLCY', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Extract Amount (LCY)')),
                ('payee', models.BooleanField(default=False)),
                ('currencyCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.currency', verbose_name='Currency Code')),
                ('payrollCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lookups', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Lookup',
                'verbose_name_plural': 'Lookups',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='calculationscheme',
            name='lookUp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculationSchemes', to='payroll_setup.lookup', verbose_name='LookUp'),
        ),
    ]
