# Generated by Django 5.2.6 on 2025-09-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0017_calculationscheme_calculateto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationscheme',
            name='fCalculation',
        ),
    ]
