# Generated by Django 5.2.6 on 2025-09-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_setup', '0018_remove_calculationscheme_fcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationscheme',
            name='payrollLines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputCalculationSchemes', to='payroll_setup.eddefinition', verbose_name='Payroll Lines'),
        ),
    ]
