# Generated by Django 5.2.5 on 2025-09-30 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payrollCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salaryScales', to='payroll.payroll', verbose_name='Payroll Code')),
            ],
            options={
                'verbose_name': 'Salary Scale',
                'verbose_name_plural': 'Salary Scales',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryScaleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payrollCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salaryScaleSteps', to='payroll.payroll', verbose_name='Payroll Code')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='payroll.salaryscale', verbose_name='Scale')),
            ],
            options={
                'verbose_name': 'Salary Scale Step',
                'verbose_name_plural': 'Salary Scale Steps',
                'ordering': ['scale__code', 'code'],
            },
        ),
    ]
