# Generated by Django 5.2.6 on 2025-09-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('payroll', '0002_salaryscale_salaryscalestep'),
        ('payroll_setup', '0019_calculationscheme_payrolllines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNo', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Employee No.')),
                ('name', models.CharField(max_length=255)),
                ('basicPay', models.CharField(choices=[('None', 'None'), ('Fixed', 'Fixed'), ('Scale', 'Scale')], default='None', max_length=10, verbose_name='Basic Pay')),
                ('fixedPay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fixed Pay')),
                ('calculationScheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll_setup.calculationheader', verbose_name='Calculation Scheme')),
                ('modeOfPayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employee.modeofpayment', verbose_name='Mode of Payment')),
                ('payrollCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll.payroll', verbose_name='Payroll Code')),
                ('salaryScale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll.salaryscale', verbose_name='Salary Scale')),
                ('scaleStep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='payroll.salaryscalestep', verbose_name='Scale Step')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employeeNo'],
            },
        ),
    ]
