# Generated by Django 5.2.6 on 2025-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('no', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='No.')),
                ('name', models.CharField(max_length=255)),
                ('indentation', models.IntegerField(default=0)),
                ('income_balance', models.CharField(blank=True, choices=[('Income', 'Income'), ('Balance', 'Balance')], max_length=255, null=True, verbose_name='Income/Balance')),
                ('accountcategory', models.CharField(blank=True, choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Income', 'Income'), ('Expense', 'Expense')], max_length=255, null=True, verbose_name='Account Category')),
                ('debit_credit', models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10, null=True, verbose_name='Debit/Credit')),
                ('accounttype', models.CharField(blank=True, choices=[('Posting', 'Posting'), ('Heading', 'Heading'), ('Total', 'Total'), ('Begin-Total', 'Begin-Total'), ('End-Total', 'End-Total')], max_length=255, null=True, verbose_name='Account Type')),
                ('totaling', models.CharField(blank=True, max_length=255, null=True, verbose_name='Totaling')),
                ('direct_posting', models.BooleanField(default=False, verbose_name='Direct Posting')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked')),
            ],
            options={
                'verbose_name': 'G/L Account',
                'verbose_name_plural': 'G/L Accounts',
                'ordering': ['no'],
            },
        ),
    ]
